### ISSUE TITLE
Mode inclusion ?

### ISSUE THREAD

**Issue by jerome83136** [jyvern/rfp2mqtt#5]
Hello,

Désolé par avance si ma question est stupide; mais je me demande comment réaliser l'appairage entre les appareils en le RF Player en utilisant "rfp2mqtt" ?

Actuellement j'utilise le RF Player avec Jeedom (que j'envisage donc de remplacer par rfp2mqtt).
Dans Jeedom il faut réaliser "l'inclusion" des appareils pour les associer avec le RF Player; donc je suppose qu'il faut faire la même chose ici non ?

Comment doit-on faire SVP ?

Merci d'avance

Bien cordialement

**Comment by jyvern** [comment]
Bonjour,

Il n'y a pas de questions stupides, juste des explications sans doute 
pas suffisamment claires ;-)

Pour les échanges qui nécessitent un appairage (par exemple moteur de 
volet Somfy), ca ne se fait pas dans rfp2mqtt mais avec le logiciel 
fournit pour la configuration du module RFP1000 (ici le lien 
<https://myrfplayer.com/index.php/download/rf-player-configurator/?wpdmdl=673&refresh=6024273a45eac1612982074> 
)
Une fois l'appairage fait, il faut renseigner le fichier de config avec 
ces infos. En activant plus de traces (ie on met level à debug) vous 
pourrez controler ce qui est reçu et fait.

Dispo pour en échanger si besoin

Cdt
Jean-Yves

**Comment by jerome83136** [comment]
Bonjour,

Merci pour cette sympathique réponse :)

Est-ce que le "configurator" est utilisé pour:
- Appairer le RFP1000 avec l'appareil qu'on souhaite piloter ? (dans ce cas j'en déduis que c'est dans une mémoire interne du RFP1000, que appairage avec l'appareil est conservé)
OU pour
- Récupérer les infos échangées entre le RFP1000 et l'appareil à appairer; informations qu'on réutilise ensuite pour configurer rfp2mqtt

Question bonus (dont vous vous douterez): est-il prévu que rfp2mqtt permette de "piloter" l'association du RFP1000 avec des appareils; sans passer par le configurator ?

Merci d'avance pour votre aide
Bien cordialement

**Comment by jyvern** [comment]
Bonjour,

Le "configurator" sert en effet à appairer les capteurs qui en ont 
besoin (genre SOMFY RTS)
Il peut servir aussi à des fins de test.

Une fois l'appairage fait, on retrouve dans les traces des échanges 
entre le RFP1000 et le capteur et on se sert de ces données pour 
préparer le fichier de conf. Je pourrais sans doute mieux vous aider 
si vous me donniez plus d'infos sur les capteurs concernés.

Je n'ai pas prévu d'aller plus loin dans le développement de rfp2mqtt 
sauf à y inclure la prise en compte de nouveaux 
protocoles/périphériques (rfp2mqtt ne prend en charge que rts,  
oregon, X2D ). Donc pas de travaux de prévus sur l'enrôlement via des 
commandes MQTT.

De plus, j'avoue que je suis tenté de remplacer rfp2mqtt par l'usage 
de Home Assistant et le plugin développé pour le RFP1000.

Cdt
Jean-Yves

**Comment by jerome83136** [comment]
Bonjour,
Merci pour votre retour.
Je n'ai malheureusement pas le temps de tester pour l'instant; mais ne manquerai pas de faire un retour ASAP.

En attendant; je ferme ce ticket pour ne pas polluer :)

Bien cordialement
